version: 0.1
   
phases:
  install:
    commands:
      - apt-get update && apt-get install -y --no-install-recommends build-essential libssl-dev wget python python-dev
      - gem update
      - gem install jekyll jekyll-watch
  build:
    commands:
      - echo "******** Building coming soon page ********"
      - jekyll build
      - echo "******** Updating coming soon page to s3 bucket ->  ********"
      - echo "s3://serverless-tutorials.com"
      - aws s3 sync _site/ s3://serverless-tutorials.com/
